componentsVersion: VERSION
projects:
  concept-base:
    description: A component for basic interfaces needed by multiple components and
      that do not warrant a standalone component.
    path: components/concept/base
    publish: true
    upstream_dependencies:
    - support-test
  concept-fetch:
    description: An abstract definition of an HTTP client for fetching resources.
    path: components/concept/fetch
    publish: true
    upstream_dependencies:
    - support-test
  concept-engine:
    description: An abstract layer hiding the actual browser engine implementation.
    path: components/concept/engine
    publish: true
    upstream_dependencies:
    - browser-errorpages
    - concept-fetch
    - concept-storage
    - support-base
    - support-ktx
    - support-test
    - support-utils
  concept-storage:
    description: An abstract definition of a browser storage layer.
    path: components/concept/storage
    publish: true
    upstream_dependencies:
    - support-ktx
    - support-test
  browser-errorpages:
    description: Responsive browser error pages for Android apps.
    path: components/browser/errorpages
    publish: true
    upstream_dependencies:
    - support-ktx
    - support-test
    - ui-icons
  ui-icons:
    description: A collection of often used browser icons.
    path: components/ui/icons
    publish: true
    upstream_dependencies: []
  service-glean:
    description: A client-side telemetry SDK for collecting metrics and sending them
      to the Mozilla telemetry service
    path: components/service/glean
    publish: true
    upstream_dependencies:
    - concept-fetch
    - lib-fetch-httpurlconnection
    - lib-fetch-okhttp
    - support-base
    - support-ktx
    - support-test
    - support-utils
  support-base:
    description: Base component containing building blocks for components.
    path: components/support/base
    publish: true
    upstream_dependencies:
    - concept-base
    - support-test
  support-ktx:
    description: A set of Kotlin extensions.
    path: components/support/ktx
    publish: true
    upstream_dependencies:
    - lib-publicsuffixlist
    - support-base
    - support-test
    - support-test-fakes
    - support-utils
  support-test:
    description: A collection of helpers for testing components (local unit tests).
    path: components/support/test
    publish: true
    upstream_dependencies:
    - support-base
    - support-ktx
  support-test-fakes:
    description: A collection of fake implementations for testing purposes.
    path: components/support/test-fakes
    publish: true
    upstream_dependencies:
    - concept-engine
  support-android-test:
    description: A collection of helpers for testing components from instrumented
      (on device) tests.
    path: components/support/android-test
    publish: true
    upstream_dependencies: []
  support-utils:
    description: A collection of generic helper classes.
    path: components/support/utils
    publish: true
    upstream_dependencies:
    - support-base
    - support-test
  lib-fetch-httpurlconnection:
    description: An implementation of lib-fetch based on HttpUrlConnection.
    path: components/lib/fetch-httpurlconnection
    publish: true
    upstream_dependencies:
    - concept-fetch
    - tooling-fetch-tests
  lib-fetch-okhttp:
    description: An implementation of lib-fetch based on OkHttp.
    path: components/lib/fetch-okhttp
    publish: true
    upstream_dependencies:
    - concept-fetch
    - support-test
    - tooling-fetch-tests
  lib-publicsuffixlist:
    description: A library for reading and using the public suffix list.
    path: components/lib/publicsuffixlist
    publish: true
    upstream_dependencies:
    - support-test
  tooling-detekt:
    description: Custom Detekt rules for internal use.
    path: components/tooling/detekt
    publish: false
    upstream_dependencies: []
  tooling-lint:
    description: Custom Lint checks for using and writing components.
    path: components/tooling/lint
    publish: false
    upstream_dependencies: []
  tooling-fetch-tests:
    description: Test cases for concept-fetch implementations.
    path: components/tooling/fetch-tests
    publish: false
    upstream_dependencies:
    - concept-fetch
  tooling-glean-gradle:
    artifact-type: jar
    description: A Gradle plugin to generate code for Glean metrics.
    path: components/tooling/glean-gradle-plugin
    publish: true
    upstream_dependencies: []
